library(devtools)
library(dplyr)
library(tidyr)
library(reshape2)
library(monocle3)
library(ggridges)
library(UpSetR)

N7_bcs = list(plate1 = c("TTAGGCGTCC", "GGTCTAACTG", "ATTGAGACGG", "AACGTACCAT", "GTTCAGTTAC", "GTTAACCTTA", "GGAGTAGTAG", "CAGGTTGAGA", "AACCAATAAC", "GGTACCTATT", "AGCTGCCTCA", "TTGGTTGGTA", #A
                         "CTGATATCGG", "TTGATGGAAC", "GGACCAGAAG", "ACCTGAGGTC", "TTGCAATGAG", "ACTAACTGAC", "GGTAAGAGGT", "GTAATCGCAA", "ATATGATGAA", "CCTACGGAAG", "GACTCTCCGA", "ATAGATACGT", #B
                         "TATGAAGCAA", "GTAGAGACGA", "TTCGCATAAC", "TAGATTCGCC", "TTCTTCGCGG", "TTCTTGGTCT", "GTATAGATTA", "GACTATGACT", "GCTCCGCGAA", "GGAACGATTC", "GTACCTTCGT", "TTATGCGACT", #C
                         "AACGGTTGGT", "CTAGAAGGAA", "GTATGGAGGA", "CGTAAGTAGC", "TAGTCGTCAA", "GTAGTATGGA", "AATGGACGTA", "CCGTTCGCTG", "CAGTCAATAT", "GTCGGACTGA", "TTCCATGCGC", "GGACGGCATG", #D
                         "GGAGCAACGT", "CGTCCTAGCT", "ATATTAGTAG", "AGTTCCTTCT", "GCCTTCAAGG", "TAACGCCTCA", "GAATACGTCT", "GATGAGCCTT", "TACGGAGACT", "AGAGGTCATT", "CGGCCAGTTA", "TAGCGCTTAA", #E
                         "CAACCTTATG", "CTTCGACGAA", "AGAGTCCGAG", "CTATGGTTCG", "AACTATTGGC", "CTTGCGAGGT", "TTCGGCTCGT", "CTCAAGTCTG", "ATTAGGCCTG", "TGGCTAACGT", "AGCTAATATT", "AGGAATCTTC", #F
                         "AAGACCAGAC", "ACCATAAGCG", "TGCTTATTAC", "ATAGAGCATT", "AATTATCTTG", "GTTCCGCGCG", "CCGAAGTCCG", "TTACCATGAT", "TATAGATGGC", "GCATATCTGG", "ACTCTAGAAG", "CAAGAATATG", #G
                         "CTGCTGCGCG", "CATATTACGG", "CGGCGGAATG", "TGCTTCTGAA", "GTATTCTTCT", "CAGTAGTAAT", "CCGCGGAGAC", "GCTCGTCGGC", "CTTAGAGGCA", "GACCAAGACG", "AGCAGATGGT", "AATTAACCAT"),#H
              plate2 = c("CAGACTCGCT", "CTTCGCCGTT", "CCTGCCAACC", "GAGATCGCGG", "AATTGCCGTC", "GCGCGGTCCG", "GCGAAGGCTC", "CATCGACTCA", "CTCGGTTGCA", "GTTAAGTATT", "AGTTCCGGAC", "CAGCGGTCGG",
                         "GACGCGGTAG", "TTCTTCTATT", "CAATTATAGT", "ATAGGAGTTC", "GTTATTAATT", "ATGATCGCCA", "ATCATCAGAA", "GTTCGGCCTT", "TTACGTCTAG", "GCTGCATAGC", "TGATTGCTTC", "TAACTTGGAG",
                         "AACTTACGCT", "GGTTCGTACC", "CGCTCCTTGG", "GCTTGCGCGT", "AATCTAGTCC", "TTGGAGAACG", "GGTAGTCTTA", "TGGAACCGTA", "GAGTTAAGGT", "GTTATCGGTA", "CTACGAGTCG", "CCTAATTCTG",
                         "TGCCTTGACG", "TCTAATTATT", "CGCAACCTGG", "AGGCGGTCTC", "TCTCGTTGAG", "AATTACTAAT", "CTATCCGGAG", "TTCGTTCCTG", "CGACCTATAC", "CTGGCTTAGT", "TACGCCGTAT", "GAGTCCTGCA",
                         "TGGCGCAACT", "CCGTCTACTA", "AGGCTGATTA", "CTCCATAATC", "ATTACGTAGG", "ACGTATGCGC", "GTCTAATAGG", "TCAGAACGAC", "GTCCAGTCGT", "TGATGCTGAT", "CGCGTTACCT", "TCTCTGATCG",
                         "GGTATCATCT", "GCCTGGCAGT", "TGGTTACGCT", "CCTACCGTCC", "CGCTCCAGAA", "TTCCGCGTTA", "CCGACGCGCC", "GATCTTATCC", "CGCGAGGATG", "TGGAATATAG", "GCGGCTACTC", "GTTATGAGAA",
                         "CAACGTTGCC", "AGTAGCCTTG", "GCCGGTTAAC", "AAGATATAGA", "TCTCAGCGGC", "TCCAAGGAGA", "GACCAATTCT", "GGACCTTGCA", "TGATCAATTA", "TTCTCCGCTA", "TTGGACGCGG", "AACTGCTAAG",
                         "CGAGTCGAAG", "TCAGGATTAA", "AAGGACCTTA", "TCCTCTTAAC", "TCATAGGCTT", "GTTACGACTC", "GAGGTCCAGT", "GGAAGTCTGG", "CATGATCGTT", "CTCATGATTG", "GGCAGAGGAG", "GTTCTAGCCA"),
              plate3 = c("CAGCGGATAA", "GCGAGAGAAG", "TGAATAACTA", "TGGAGAGGCC", "GAGGACCGAT", "CGCTGGCAAG", "CTTGATTCAA", "TTCCTCAAGG", "TACTGGATAA", "GGATGGTCCG", "TGCGCGGCAT", "AGCGCGGAAC",
                         "CTGGATGCCA", "TTATCTTATT", "GTCTTGATGC", "TGGTCAAGAT", "CCGTCAGTTG", "TGACCTTAAT", "CTGATTCTCT", "CCTTCCTTCA", "CATACGGATT", "GAGCTTAGAA", "CTTATCGCAG", "CCGGCAATCC",
                         "GTTCTATTGG", "CAATCGACGG", "GGAGGAGCTT", "GGTTATATTA", "GATGGTTACC", "AGCGTCTGGT", "ATGGTACTCT", "CGTAGGTTGG", "ATCGGTTCCG", "ATAGGTTATC", "CGAGGCTACC", "GCCATAGTAG",
                         "GGCCGTTGAT", "TTCGACCAGA", "CGCCTAGAGA", "GTTCTCCGGA", "CGCCTCGGCG", "TGGATCTGCA", "GTCTATACCA", "TTATCCATCC", "TGGACCGCCA", "ACTCGCCGCT", "TAGCATTGAT", "GTCATCGACC",
                         "GTATAACTCC", "CGGCGAGTCC", "AGCCTGACTG", "ACGAGCCTCT", "ATGAAGGAGG", "TGCTTCCGCC", "ATGCGCGAGT", "TATGAGTTGA", "ATGGCTCGGT", "GCTGGCTGAA", "CTGGATTGGA", "GTTGGCATGG",
                         "AGAATGCTGG", "GGAGAGATCC", "GTCAACTAAT", "GGTACCAACC", "ACGGCAAGCA", "CCGGATTACT", "GAAGGTTCGG", "AGTAAGTTAC", "GGCCTAGCGG", "ACTGATGAGT", "GCGGTCAGAG", "TAGGTATGAA",
                         "GAGGCAAGGC", "TTCGAACGTC", "GTCCTGCCGA", "TAGGCGATAT", "GAACCTCTAA", "GGAACGCCTA", "GGTATTAGCG", "TGCAAGCGCG", "CCAACTGAAT", "GGCATATATA", "AGCCGAGGAC", "AATGCTCTGA",
                         "GTATTGAAGT", "TTAATGACTT", "GTATCTCGAT", "AGCCGTTCCA", "GTACGATACT", "ATGGTTAGAA", "CCTTGGCGAA", "TTGGCTACTA", "CCGGAGGACC", "AGAGAGTTGG", "TTACGCCATT", "ATATGCCGCG"),
              plate4 = c("CCTGGATAGT", "GAGGCGTAAT", "CGACGGAGGC", "ATAAGTCGAA", "TCGAGGTCTT", "TCAGACTGGA", "GTCGATTATG", "CAGGACCAGC", "GCGCAGGCGA", "GTTAGCTAAG", "CTACCATCTC", "CTTACTTCCT",
                         "GACTTCTACT", "TAACCGCTGA", "CTTGCCAATA", "ATAGTATTGC", "CCGCGGTCAA", "ATCTCCTGAA", "CGGACCGGTA", "ATAACCGTCC", "TTCTGATTAA", "GCCTACGTTC", "CATTGATACC", "AAGTCTTCTG",
                         "AGTTATTGAC", "ATTAGTAACG", "GTCATATTCG", "CGACTTCGGA", "TATCGTAGGA", "ACCGCTCAAC", "AGCTGCGTTG", "TATTATTGGT", "GCTATGCGAT", "TAGGCTTCGA", "CGTATCTGCT", "TGGTTGAGGA",
                         "GTTCCAACTT", "CATGGCGTCA", "GTCGTTGCTT", "ATTATACTAC", "CGAATAGTTG", "GGTAATGGAC", "GGAGTCCATT", "GATGAACGGT", "GCGGTCTTAT", "CTCCGAATGC", "TGAGAACTTG", "ACTCCGACCA",
                         "TAATCCTCTT", "CAGTATGGTC", "ACGTCTCCTC", "CTCCAGGCGG", "AAGATTCCTC", "TCTCGAAGGC", "ACTAGTCTCG", "TCCAGCTCTC", "TAACCTGCAA", "GTTCTGACGT", "CCAAGGTCGG", "CGTTACTTAG",
                         "CGGCATGGAC", "GTCTGCGCTT", "TGAATTATGA", "AAGCCGGTAA", "CGCATTAATT", "GGCCGACCGT", "AGCGAAGTAG", "GGCCATACTT", "GAGAGTTAAC", "GTTGGCGACC", "AGGTTATACC", "TTCTATAGTT",
                         "GAGGTCTGAC", "GAGAATGAAG", "GTCCGCAGTA", "TTGGTTAACC", "TTATGGCCGG", "CAGACTTCAT", "GTCGCTGGAG", "TCGAGAAGGT", "TCGGCGTACC", "CAACGCCTGG", "GCTGCCATTC", "AAGTTCGTAA",
                         "TCATGCTCAG", "TATCTCTCAT", "GAGGCTTGGT", "ACCAATATGG", "GGAACTGAGC", "GCCGAACTGC", "TAATACGGAC", "GGATATACGG", "TTACTCTCTT", "CGCAACGCCA", "GTATAAGGCA", "AGATAATTCC"))

P7_bcs = c("GAATGCCTTG", "CGGACTGGCC", "CTGGCAGCGG", "TCATCAGCCA", "TAACCAGTTA", "AGCTCATTCG", "CAACGGTCTT", "TGGTATCAGA", "GGTAACTACG", "CTTCAGGCCA", "ATCCTTCAAC", "TGATTGAATG", #A
           "TGCTTAGCGA", "CGAGTTCGCC", "CGGCATCTTG", "TCAACGAGGT", "GGTCTAGGAA", "AAGTCAACGG", "TAACCAATCG", "ATCGGCTTGA", "CAATCTCAAT", "CAGTTGCTTG", "ATGCTAACCT", "CGGATCTCCG", #B
           "TGACGCGACC", "TCTGACGAAC", "GATCATGATA", "TTCTCTACGA", "TACGCAGGTT", "TGCGAATCGG", "CTAAGAGTTA", "TCCATACCTG", "ACCGGTCTGC", "TAGAACCTCC", "TGACCATCAG", "GACTCGAGGA", #C
           "GCATTAGGCG", "GGACTTATGG", "TTGGTTCTCA", "TAATTCCGGT", "CTACTGCAAG", "CGTAGCCGTA", "TTGACTTCGT", "TCAGCGCAAT", "ATATGGTACC", "TGCCGGTACC", "GGTACTTCCA", "AATTGAGTTA", #D
           "GCGGCGCAAG", "AATACCTGCC", "AGCATACGGC", "GCCTCGGTAA", "ACGGACCTGC", "CATTCTGATG", "GCTTACTATA", "TCCAATGGTT", "ACGGTAATTG", "TCGGAGTATG", "GGTTAGTTGG", "CTGCATTACG", #E
           "TGCGGCCTGG", "CATCTATTCG", "GCAGCTGATT", "ATATCTTCCG", "GTCGTACGCG", "TTGATGCCTC", "TTGGAACTGG", "GGAGAATGGC", "TTCCATTCTT", "CCGAAGGTTA", "CCGGCTGAGC", "ACGAGGAGCC", #F
           "AAGATCAGTT", "ATCCGAACGG", "CTGCGCTGGT", "TGCCATGGAA", "AGCTGAACGC", "GAGACGTTCT", "CTGACTACTT", "CGCCGATATC", "TGGATCGTTA", "GTACCTGAAT", "GAATTCTCCA", "AGACCAGGTT", #G
           "CTAGCTTCTT", "GGCAACCTTC", "CCGTTAGCAA", "GGCGTCTGCC", "CGCGCAACCG", "AGTCTTAATT", "TAAGGAACGG", "TCGTTCATTA", "ACTCCAGATT", "CGATATATCT", "GGCTGGCTCT", "GGCGGATACC") #H

P5_bcs = c("CAAGGAGGTC", "CTGAACTGGT", "TGCGCCAGAA", "CTTGATTGCC", "ACCTGGCCAA", "CAGGAGGAGA", "ACTACTGAAG", "ACTTAACCTT", #1
           "CCGCGGCTCA", "AAGACGGCCA", "AGAGAAGGTT", "CGATGGCGCC", "AATGGTCGAC", "CTTGGTAATG", "ACTTAACTAG", "ATGCAATATG", #2
           "TTGCCTTGGC", "GTTATGGATC", "TGGTATTCAT", "TTAGCAATAA", "GCAAGGAATA", "AGCCGGTACC", "CAACCAGTAC", "ATCATCAACG", #3
           "GAAGAGGCAT", "TTCAATATAA", "TCAGACGAAC", "TTATCCGGAT", "GATAAGGCAA", "CTAACTAGAT", "ACCTCTATCT", "CGGATTAGAA", #4
           "AATCCATCTT", "TTACTTGGAA", "CAAGCTTCAT", "CTCCAAGGAT", "GATACGGAAC", "CCGCTCCGGC", "TGCGCCATCT", "TTCTTAATAA", #5
           "CCTGGAAGAG", "CAACCGCTAA", "TAGATCTACT", "ATATTGATAC", "ACCGAAGACC", "ATAGACTAGG", "AGTAACGGTC", "AGTAAGCATA", #6
           "CCGATTCCTG", "CCTTACTCCT", "GCTAACCTCA", "TGCGCGATGC", "CCTGACGTTC", "GTCCAACTCA", "TTGATGCTAT", "TGGAACTAGA", #7
           "TATAGACGCA", "GGCTCTCTAT", "CTGATTAAGA", "AAGTCTTCCG", "TGAGTCTGGC", "AAGCCAGTTA", "TGATGGCCTT", "TTACGTATAC", #8
           "ATGGAATTGG", "CCGCTATATT", "CGCCTCGAAC", "CCTAGTACGT", "CAGATTCGAT", "GCGACGCAGA", "GGCGAGCTTA", "CGGTTATGCC", #9
           "CGACGCGACT", "CCTTGGTCCA", "CTCTGATCAG", "GGCAATGAGA", "TATGCCGAGT", "GGCTGAGCTC", "TATCCTCAAT", "GTTCCGCTAA", #10
           "CGGATGAAGG", "AACTGCTGCC", "TACTTACTTA", "GACCTTGATA", "TTCCAACCGC", "TTATTCATTC", "AATACTCTTC", "AGCTAAGGTA", #11
           "TTGACTGACG", "AACTAGGCGC", "GGACTACTAC", "GACGAAGCGT", "ATCGGCTATC", "ATCCATGACT", "GTCCTTAAGA", "TTAGGACCGG") #12




get_N7_well = function(seq, bcList = N7_bcs){
  N7bc = stringr::str_sub(seq, 1,10)
  for (i in 1:length(N7_bcs)) {
    if (N7bc %in% N7_bcs[[i]]) {
      PLATE = N7_bcs[[i]]
      break;
      }
    }
    pos = match(N7bc, PLATE)
    row = ifelse(pos %% 12 == 0, floor(pos / 12), floor(pos / 12) + 1)
    col = ifelse(pos %% 12 == 0, 12, pos %% 12)
    row_col = paste0("plate", i, "_", LETTERS[row], ifelse(col >= 10, col, paste0("0", col)))
    return(row_col)
}


get_PCR_well = function(seq, P7List = P7_bcs, P5List = P5_bcs){
  P7bc = stringr::str_sub(seq, 11,20)
  P5bc = stringr::str_sub(seq, 31,40)
  P7pos = match(P7bc, P7_bcs)
  P5pos = match(P5bc, P5_bcs)
  P7row = ifelse(P7pos%%12 == 0, P7pos/12, floor(P7pos / 12) + 1)
  P7col = ifelse(P7pos%%12 == 0, 12, P7pos %% 12)
  P5row = ifelse(P5pos %% 8 == 0, 8, P5pos %% 8)
  P5col = ifelse(P5pos %% 8 == 0, P5pos/8, floor(P5pos / 8) + 1)
  row_col = paste0(LETTERS[P7row], ifelse(P7col >= 10, P7col, paste0("0", P7col)), "_", LETTERS[P5row], ifelse(P5col >= 10, P5col, paste0("0", P5col)))
  return(row_col)
}


